<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login Test"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="20.226">
  <properties />
            <testcase name="bankManagerShouldAddCustomerSuccessfully" time="1.455" classname="com.bank.testsuite.BankTest">
                <failure type="java.lang.AssertionError"
                  message="expected [2] but found [1]"
              >
<![CDATA[java.lang.AssertionError: expected [2] but found [1]
  org.testng.Assert.fail(Assert.java:110)
  org.testng.Assert.failNotEquals(Assert.java:1413)
  org.testng.Assert.assertEqualsImpl(Assert.java:149)
  org.testng.Assert.assertEquals(Assert.java:131)
  org.testng.Assert.assertEquals(Assert.java:1240)
  org.testng.Assert.assertEquals(Assert.java:1274)
  com.bank.testsuite.BankTest.bankManagerShouldAddCustomerSuccessfully(BankTest.java:41)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(ArrayList.java:1249)
  org.testng.TestRunner.privateRun(TestRunner.java:808)
  org.testng.TestRunner.run(TestRunner.java:603)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
  org.testng.SuiteRunner.run(SuiteRunner.java:326)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.runSuites(TestNG.java:1092)
  org.testng.TestNG.run(TestNG.java:1060)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="bankManagerShouldOpenAccountSuccessfully" time="11.385" classname="com.bank.testsuite.BankTest" />
                <testcase name="customerShouldDepositMoneySuccessfully" time="3.125" classname="com.bank.testsuite.BankTest" />
                <testcase name="customerShouldWithdrawMoneySuccessfully" time="2.428" classname="com.bank.testsuite.BankTest" />
                <testcase name="customerShouldLoginAndLogoutSuccessfully" time="1.833" classname="com.bank.testsuite.BankTest" />
      
</testsuite>
